"""Editorial upgrades for high-demand careers that started as EXTRA_CAREERS placeholders.

Applied on every boot by content_seed.seed_app_content. Existing slugs are updated
in place so a live database picks up the new copy without clear_db.
"""

# 35+ careers Indian Class 10–12 students actually search for.
NEW_VERIFIED = [
    dict(
        slug="company-secretary-with-qualification",
        name="Company Secretary (CS)", cluster="business",
        description="Advises boards on company law, governance, listings and secretarial compliance. A statutory officer in many Indian companies.",
        demand="High", salary_min=450000, salary_max=1800000,
        skills="Company Law, Corporate Governance, Drafting, Compliance",
        ai_impact="Filing templates are automated; board advice and governance judgment stay human.",
        education_path="ICSI CSEET after Class 12 → Executive → Professional + training. Commerce helps but any stream can start.",
        exams="CSEET, CS Executive, CS Professional",
        riasec="CE", wlb="Demanding", remote="Hybrid",
        mid=(800000, 1800000), senior=(1500000, 3500000),
        related=["chartered-accountant", "cost-accountant", "lawyer"],
        institutes=[
            ("ICSI CS course (any city)", "Professional", "CSEET", "Exam + practical training"),
        ],
        steps=[
            ("After Class 10", "Commerce is the usual path; PCM/Arts students also switch.", 1),
            ("After Class 12", "Register for CSEET. Keep accounts and business studies strong.", 2),
            ("Skill Development", "Company law, SEBI LODR basics, board-note drafting.", 3),
        ],
    ),
    dict(
        slug="cost-accountant",
        name="Cost and Management Accountant (CMA)", cluster="business",
        description="Plans and audits costs, budgets and management accounts for factories, PSUs and corporates.",
        demand="High", salary_min=400000, salary_max=1600000,
        skills="Costing, Budgeting, SAP/Excel, Management Reporting",
        ai_impact="Spreadsheets automate; cost strategy and shop-floor judgment remain human.",
        education_path="ICMAI CMA Foundation after Class 12 → Intermediate → Final + training.",
        exams="CMA Foundation, CMA Intermediate, CMA Final",
        riasec="CI", wlb="Average", remote="Mostly On-site",
        mid=(700000, 1500000), senior=(1300000, 2800000),
        related=["chartered-accountant", "company-secretary-with-qualification"],
        institutes=[
            ("ICMAI CMA course", "Professional", "CMA Foundation", "Strong in manufacturing and PSUs"),
        ],
        steps=[
            ("After Class 10", "Commerce or PCM. Maths helps.", 1),
            ("After Class 12", "CMA Foundation, or CA + CMA together if you can handle the load.", 2),
            ("Internships", "Costing internship in a plant or PSU.", 3),
        ],
    ),
    dict(
        slug="actuary",
        name="Actuary", cluster="business",
        description="Prices insurance, pensions and risk using probability and finance. One of the scarcest quantitative careers in India.",
        demand="High", salary_min=700000, salary_max=3000000,
        skills="Probability, Financial Maths, Excel/R/Python, Insurance Products",
        ai_impact="Models run faster; assumption-setting and regulation stay human.",
        education_path="Any degree with strong maths. IAI/IFOA exam series while you work. B.Sc Stats/Math or B.Com (H) helps.",
        exams="IAI ACET, IAI/IFOA Core Principles papers, CUET for the bachelor's",
        riasec="IC", wlb="Good", remote="Hybrid",
        mid=(1500000, 3500000), senior=(2500000, 6000000),
        related=["statistician", "economist", "data-analyst"],
        institutes=[
            ("Institute of Actuaries of India", "Professional", "ACET + IAI papers", "Pass-by-paper; 5–8 years typical"),
            ("B.Sc Statistics / Maths (ISI, CMI, good universities)", "University", "CUET / institute", "Best undergraduate base"),
        ],
        steps=[
            ("After Class 10", "Keep maths. Commerce or PCM both work.", 1),
            ("After Class 12", "A quantitative bachelor's. Sit ACET when ready.", 2),
            ("Skill Development", "Clear Core Principles while interning at an insurer or consulting firm.", 3),
        ],
    ),
    dict(
        slug="probationary-officer",
        name="Bank Probationary Officer (PO)", cluster="business",
        description="Officer-level role in public and private banks: credit, operations, customer desk, then specialist or scale-up.",
        demand="High", salary_min=550000, salary_max=1200000,
        skills="Quantitative Aptitude, Banking Awareness, Communication, Credit Basics",
        ai_impact="Branch ops automate; credit judgment and customer trust stay human.",
        education_path="Any bachelor's degree. Then IBPS PO, SBI PO or bank-specific exams.",
        exams="IBPS PO, SBI PO, IBPS RRB Officer",
        riasec="EC", wlb="Average", remote="Completely On-site",
        mid=(800000, 1400000), senior=(1200000, 2200000),
        related=["rbi-grade-b", "economist"],
        institutes=[
            ("Any recognised bachelor's + bank exam", "Exam", "IBPS / SBI PO", "Graduation required; age caps apply"),
        ],
        steps=[
            ("After Class 10", "Any stream.", 1),
            ("After Class 12", "Any bachelor's. Start quant + English practice in year two.", 2),
            ("First Job", "IBPS/SBI PO after graduation. Treat clerk exams as a backup, not the goal.", 3),
        ],
    ),
    dict(
        slug="rbi-grade-b",
        name="RBI Grade B Officer", cluster="business",
        description="Direct-recruit officer at the Reserve Bank of India — monetary policy, regulation, supervision and currency management.",
        demand="High", salary_min=1200000, salary_max=2500000,
        skills="Economics, Finance, Essay Writing, Data Interpretation",
        ai_impact="Low displacement; the role is policy and regulation.",
        education_path="Bachelor's with minimum marks (check the year's notification). Many also hold MA Economics or MBA.",
        exams="RBI Grade B (Phase I, II, interview)",
        riasec="IE", wlb="Good", remote="Mostly On-site",
        mid=(1800000, 2800000), senior=(2500000, 4000000),
        related=["probationary-officer", "economist", "civil-services"],
        institutes=[
            ("Any good bachelor's; MA Economics is common", "University / exam", "RBI Grade B", "Notification is yearly; age and attempts capped"),
        ],
        steps=[
            ("After Class 10", "Any stream; economics later helps.", 1),
            ("After Class 12", "BA/B.Sc Economics, B.Com or any degree + serious reading habit.", 2),
            ("During Graduation", "RBI Grade B is after graduation. ESI and FM optional-style prep takes a year.", 3),
        ],
    ),
    dict(
        slug="state-pcs-officer",
        name="State Civil Services (PCS / SSE)", cluster="law",
        description="State administrative service — SDM, DSP, commercial tax and other state cadres via the State PSC.",
        demand="High", salary_min=560000, salary_max=1800000,
        skills="General Studies, State GK, Essay, Interview",
        ai_impact="Low AI risk; field administration is human work.",
        education_path="Any bachelor's. Then your State PSC (UPPCS, MPSC, BPSC, CGPSC, RAS, …).",
        exams="State PSC / PCS / SSE (prelims, mains, interview)",
        riasec="ES", wlb="Demanding", remote="Completely On-site",
        mid=(800000, 1500000), senior=(1400000, 2200000),
        related=["civil-services", "civil-judge"],
        institutes=[
            ("Any recognised bachelor's", "University", "State PSC", "Domicile rules often apply; UPSC is the national cousin"),
        ],
        steps=[
            ("After Class 10", "Any stream. Read, write, and follow your state news.", 1),
            ("After Class 12", "A bachelor's you can score in. Optional later can match the subject.", 2),
            ("During Graduation", "This is a graduate exam. Do not apply in Class 12. Build GS over 2–3 years.", 3),
        ],
    ),
    dict(
        slug="civil-judge",
        name="Civil Judge / Judicial Magistrate", cluster="law",
        description="Entry to the subordinate judiciary. Tries civil and criminal cases at the junior division / JMFC level.",
        demand="Medium", salary_min=700000, salary_max=1800000,
        skills="Substantive Law, Procedure, Judgment Writing, Court Craft",
        ai_impact="Research tools help; deciding cases stays human.",
        education_path="LLB (3-year or 5-year). Then State Judicial Service exam. Age and practice rules vary by state.",
        exams="State Judicial Service, CLAT (for the LLB)",
        riasec="CI", wlb="Demanding", remote="Completely On-site",
        mid=(1000000, 1800000), senior=(1600000, 2800000),
        related=["lawyer", "civil-services"],
        institutes=[
            ("NLU or any recognised LLB college", "Law school", "CLAT / university", "Then the State Judicial Service"),
        ],
        steps=[
            ("After Class 10", "Any stream. Reading and writing matter more than the stream.", 1),
            ("After Class 12", "5-year LLB via CLAT, or graduate first then 3-year LLB.", 2),
            ("During Graduation", "Moot courts, internships, and statute reading. The judicial exam is after the LLB.", 3),
        ],
    ),
    dict(
        slug="army-officer-nda-cds",
        name="Army Officer (NDA / CDS)", cluster="law",
        description="Commissioned officer in the Indian Army via NDA (after 12th) or CDS (after graduation), then IMA / OTA.",
        demand="High", salary_min=700000, salary_max=1800000,
        skills="Fitness, Leadership, General Ability, Mathematics (NDA)",
        ai_impact="Very low displacement; command is a human role.",
        education_path="NDA after Class 12 (PCM for some academies) or CDS after a bachelor's. SSB interview is decisive.",
        exams="NDA, CDS, SSB interview",
        riasec="RE", wlb="Demanding", remote="Completely On-site",
        mid=(1000000, 1800000), senior=(1600000, 2800000),
        related=["air-force-officer", "indian-navy-officer", "civil-services"],
        institutes=[
            ("National Defence Academy, Pune", "Defence", "NDA + SSB", "12th pass; PCM for Air Force/Navy wings"),
            ("IMA Dehradun / OTA Chennai", "Defence", "CDS + SSB", "After graduation"),
        ],
        steps=[
            ("After Class 10", "PCM if you want NDA Air Force/Navy options. Start running and reading.", 1),
            ("After Class 12", "NDA is the 12th-pass national exam. CDS is after graduation.", 2),
            ("Skill Development", "SSB practice, NCC if available, and a realistic fitness plan.", 3),
        ],
    ),
    dict(
        slug="air-force-officer",
        name="Air Force Officer (NDA / AFCAT / CDS)", cluster="law",
        description="Flying, technical or ground-duty officer in the Indian Air Force.",
        demand="High", salary_min=750000, salary_max=2000000,
        skills="Physics/Maths (flying/tech), Fitness, Spatial Awareness, Leadership",
        ai_impact="Aircraft systems automate; command and flying judgment stay human.",
        education_path="NDA (PCM) after 12th, or AFCAT/CDS after a relevant bachelor's. Flying branch has medical and age filters.",
        exams="NDA, AFCAT, CDS, SSB, CPSS (flying)",
        riasec="RI", wlb="Demanding", remote="Completely On-site",
        mid=(1100000, 2000000), senior=(1800000, 3200000),
        related=["army-officer-nda-cds", "commercial-pilot", "indian-navy-officer"],
        institutes=[
            ("NDA + Air Force Academy", "Defence", "NDA (PCM)", "12th-pass flying/ground path"),
            ("AFCAT after graduation", "Defence", "AFCAT + SSB", "Flying, technical and ground duty branches"),
        ],
        steps=[
            ("After Class 10", "Science PCM if you want flying or technical branches.", 1),
            ("After Class 12", "NDA, or a B.Tech/any degree then AFCAT.", 2),
            ("First Job", "Do not treat this as a private-airline shortcut. Medical standards are strict.", 3),
        ],
    ),
    dict(
        slug="indian-navy-officer",
        name="Indian Navy Officer", cluster="law",
        description="Executive, engineering or education officer in the Indian Navy via NDA, CDS, INET or university-entry schemes.",
        demand="High", salary_min=750000, salary_max=1900000,
        skills="Physics/Maths, Fitness, Leadership, Technical Systems",
        ai_impact="Ships are sensor-heavy; command at sea stays human.",
        education_path="NDA (PCM) after 12th, or CDS/INET/UES after a relevant degree.",
        exams="NDA, CDS, INET, SSB",
        riasec="RI", wlb="Demanding", remote="Completely On-site",
        mid=(1100000, 1900000), senior=(1700000, 3000000),
        related=["army-officer-nda-cds", "air-force-officer"],
        institutes=[
            ("NDA + Indian Naval Academy, Ezhimala", "Defence", "NDA (PCM)", "12th-pass path"),
        ],
        steps=[
            ("After Class 10", "Science PCM.", 1),
            ("After Class 12", "NDA, or B.Tech then CDS/INET.", 2),
            ("Skill Development", "Swimming, fitness, and SSB practice.", 3),
        ],
    ),
    dict(
        slug="registered-nurse",
        name="Registered Nurse (B.Sc Nursing)", cluster="healthcare",
        description="Provides bedside and community care in hospitals, clinics and public-health programmes. Among the most employable healthcare degrees in India and the Gulf.",
        demand="Very High", salary_min=250000, salary_max=800000,
        skills="Patient Care, Clinical Procedures, Communication, Infection Control",
        ai_impact="Records go digital; hands-on care and triage stay human.",
        education_path="B.Sc Nursing (4 years) after PCB, or GNM (3 years) then upgrade. State nursing council registration is mandatory.",
        exams="NEET-UG (many colleges), state nursing CET, AIIMS nursing",
        riasec="SR", wlb="Demanding", remote="Completely On-site",
        mid=(400000, 800000), senior=(700000, 1400000),
        related=["doctor-mbbs", "physiotherapist", "dietitian"],
        institutes=[
            ("Government college of nursing", "Nursing", "NEET / state CET", "Lowest fees; high demand"),
            ("AIIMS / central institutes", "Nursing", "Institute exam / NEET", "Very competitive"),
        ],
        steps=[
            ("After Class 10", "Science PCB.", 1),
            ("After Class 12", "B.Sc Nursing via NEET or state CET. GNM is a diploma alternative.", 2),
            ("First Job", "Register with the state nursing council. Gulf/UK exams are later options.", 3),
        ],
    ),
    dict(
        slug="dentist",
        name="Dentist (BDS)", cluster="healthcare",
        description="Diagnoses and treats oral disease. Own clinic, hospital dentistry or MDS specialisation after BDS.",
        demand="Medium", salary_min=300000, salary_max=1500000,
        skills="Clinical Dentistry, Manual Dexterity, Patient Communication, Infection Control",
        ai_impact="Imaging assists; procedures stay manual and licensed.",
        education_path="BDS (5 years incl. internship) via NEET-UG. MDS via NEET-MDS if you specialise.",
        exams="NEET-UG, NEET-MDS",
        riasec="IR", wlb="Good", remote="Completely On-site",
        mid=(500000, 1500000), senior=(1000000, 3000000),
        related=["doctor-mbbs", "physiotherapist"],
        institutes=[
            ("Government dental colleges", "Dental", "NEET-UG", "State + AIQ counselling"),
        ],
        steps=[
            ("After Class 10", "Science PCB.", 1),
            ("After Class 12", "NEET-UG. BDS is 5 years including internship.", 2),
            ("Career Growth Milestones", "NEET-MDS or a well-run clinic. First-year private pay can be modest.", 3),
        ],
    ),
    dict(
        slug="physiotherapist",
        name="Physiotherapist (BPT)", cluster="healthcare",
        description="Restores movement after injury, surgery or disability. Hospitals, sports teams and private clinics.",
        demand="High", salary_min=250000, salary_max=900000,
        skills="Anatomy, Exercise Therapy, Manual Therapy, Patient Education",
        ai_impact="Wearables help tracking; hands-on rehab stays human.",
        education_path="Bachelor of Physiotherapy (4.5 years) after PCB. MPT for specialisation. Check NCAHP / state council rules.",
        exams="NEET-UG or state/institute CET (varies by college)",
        riasec="SR", wlb="Good", remote="Completely On-site",
        mid=(400000, 900000), senior=(700000, 1600000),
        related=["doctor-mbbs", "registered-nurse", "dietitian"],
        institutes=[
            ("Government BPT colleges", "Allied health", "NEET / CET", "4.5 years incl. internship"),
        ],
        steps=[
            ("After Class 10", "Science PCB.", 1),
            ("After Class 12", "BPT via NEET or state CET.", 2),
            ("Internships", "Hospital + sports/ortho posting. Build a treatment logbook.", 3),
        ],
    ),
    dict(
        slug="dietitian",
        name="Dietitian / Clinical Nutritionist", cluster="healthcare",
        description="Plans therapeutic diets in hospitals, wellness centres and sports. Clinical posts usually want a recognised B.Sc + RD pathway.",
        demand="High", salary_min=250000, salary_max=800000,
        skills="Clinical Nutrition, Biochemistry, Counselling, Food Service",
        ai_impact="Calorie apps help; medical nutrition therapy stays licensed/clinical.",
        education_path="B.Sc Food & Nutrition / Home Science / Dietetics, then M.Sc and IDA/RD-style clinical hours where required.",
        exams="CUET, university entrance; hospital RD exams later",
        riasec="SI", wlb="Good", remote="Hybrid",
        mid=(400000, 800000), senior=(700000, 1400000),
        related=["registered-nurse", "physiotherapist"],
        institutes=[
            ("Lady Irwin, SNDT, good home-science colleges", "University", "CUET / institute", "Clinical internship is the differentiator"),
        ],
        steps=[
            ("After Class 10", "PCB or Home Science stream where offered.", 1),
            ("After Class 12", "B.Sc Nutrition/Dietetics. Avoid unaccredited weekend certificates as your only credential.", 2),
            ("Internships", "Hospital dietary department internship.", 3),
        ],
    ),
    dict(
        slug="journalist",
        name="Journalist", cluster="creative",
        description="Reports news across print, TV and digital. Beat expertise and clean writing matter more than the degree brand.",
        demand="Medium", salary_min=250000, salary_max=1200000,
        skills="Reporting, Writing, Verification, Interviewing",
        ai_impact="Drafting is faster; reporting, sources and ethics stay human.",
        education_path="BA Journalism / BJMC / any degree + a newsroom internship. English or a strong regional language is essential.",
        exams="CUET, university tests (no single national licence exam)",
        riasec="AE", wlb="Demanding", remote="Hybrid",
        mid=(400000, 1000000), senior=(800000, 2200000),
        related=["graphic-designer", "animation-artist"],
        institutes=[
            ("IIMC / ACJ / good BJMC colleges", "Journalism", "Institute test / CUET", "Clips beat certificates"),
        ],
        steps=[
            ("After Class 10", "Any stream. Write every week.", 1),
            ("After Class 12", "BJMC or any bachelor's + campus paper / YouTube news explainers.", 2),
            ("Internships", "Two newsroom internships before you graduate.", 3),
        ],
    ),
    dict(
        slug="graphic-designer",
        name="Graphic Designer", cluster="creative",
        description="Designs visual identity, social, print and brand systems for agencies, startups and in-house teams.",
        demand="High", salary_min=250000, salary_max=1200000,
        skills="Typography, Layout, Adobe/Figma, Brand Systems",
        ai_impact="Image tools speed drafts; art direction and taste stay human.",
        education_path="B.Des / BFA / any degree + a tight portfolio. NID/NIFT help but are not mandatory.",
        exams="NID DAT, NIFT, UCEED (optional)",
        riasec="AR", wlb="Average", remote="Hybrid",
        mid=(450000, 1100000), senior=(900000, 2000000),
        related=["ux-designer", "fashion-designer", "animation-artist"],
        institutes=[
            ("NID / NIFT / IIT B.Des", "Design", "NID DAT / NIFT / UCEED", "Portfolio is still the hiring test"),
        ],
        steps=[
            ("After Class 10", "Any stream. Draw and copy good layouts.", 1),
            ("After Class 12", "B.Des or a bachelor's + serious self-taught portfolio.", 2),
            ("Internships", "3–5 case studies > 40 random posters.", 3),
        ],
    ),
    dict(
        slug="fashion-designer",
        name="Fashion Designer", cluster="creative",
        description="Designs garments and collections for labels, export houses or an independent studio.",
        demand="Medium", salary_min=250000, salary_max=1500000,
        skills="Illustration, Pattern, Textiles, Collection Planning",
        ai_impact="Trend boards generate faster; fit and craft stay human.",
        education_path="B.Des Fashion at NIFT or a good private school. A strong portfolio can substitute a famous campus.",
        exams="NIFT, NID DAT",
        riasec="AE", wlb="Demanding", remote="Mostly On-site",
        mid=(450000, 1200000), senior=(900000, 2500000),
        related=["graphic-designer", "interior-designer"],
        institutes=[
            ("NIFT campuses", "Design", "NIFT entrance", "Most recognised fashion bachelor's"),
        ],
        steps=[
            ("After Class 10", "Any stream. Sketch clothes you see.", 1),
            ("After Class 12", "NIFT / NID, or a reputable private B.Des.", 2),
            ("Internships", "Export house or designer studio internship. Photograph your garments well.", 3),
        ],
    ),
    dict(
        slug="interior-designer",
        name="Interior Designer", cluster="creative",
        description="Plans residential and commercial interiors — layout, materials, lighting and site coordination.",
        demand="High", salary_min=250000, salary_max=1400000,
        skills="Space Planning, AutoCAD/SketchUp, Materials, Client Management",
        ai_impact="Renders get faster; site sense and client trust stay human.",
        education_path="B.Des Interior / B.Arch / diploma + portfolio. NATA if you go the architecture route.",
        exams="NID DAT, NIFT, NATA (if B.Arch)",
        riasec="AR", wlb="Demanding", remote="Hybrid",
        mid=(450000, 1200000), senior=(900000, 2200000),
        related=["architect", "fashion-designer", "graphic-designer"],
        institutes=[
            ("NID / CEPT / good interior B.Des", "Design", "NID / institute", "Site internships matter as much as software"),
        ],
        steps=[
            ("After Class 10", "Any stream; drawing helps.", 1),
            ("After Class 12", "Interior B.Des or B.Arch.", 2),
            ("Internships", "One site-facing internship. Learn AutoCAD and a 3D tool.", 3),
        ],
    ),
    dict(
        slug="hotel-manager",
        name="Hotel Manager", cluster="business",
        description="Runs rooms, F&B and guest operations in hotels, chains and hospitality groups.",
        demand="High", salary_min=250000, salary_max=1400000,
        skills="Operations, Guest Service, Revenue Basics, Team Leadership",
        ai_impact="PMS software helps; guest recovery and people management stay human.",
        education_path="BHM / B.Sc Hospitality (3–4 years). NCHMCT JEE for IHMs.",
        exams="NCHMCT JEE, university tests",
        riasec="ES", wlb="Demanding", remote="Completely On-site",
        mid=(450000, 1100000), senior=(900000, 2200000),
        related=["management-consultant", "product-manager"],
        institutes=[
            ("Central IHMs (NCHMCT)", "Hospitality", "NCHMCT JEE", "Best public hospitality bachelor's"),
        ],
        steps=[
            ("After Class 10", "Any stream. Languages help.", 1),
            ("After Class 12", "NCHMCT JEE for IHM, or a decent private BHM.", 2),
            ("Internships", "Industrial training in a branded hotel is the real classroom.", 3),
        ],
    ),
    dict(
        slug="commercial-pilot",
        name="Commercial Pilot", cluster="engineering",
        description="Flies commercial aircraft after a DGCA Commercial Pilot Licence. High cost of training; high pay once type-rated.",
        demand="High", salary_min=1500000, salary_max=6000000,
        skills="Flying, CRM, Navigation, DGCA Regulations",
        ai_impact="Autopilot assists; PIC responsibility stays with the human crew.",
        education_path="Class 12 PCM. Student Pilot Licence → CPL at a DGCA-approved flying school. Airline type rating after that. Medical Class 1 is mandatory.",
        exams="DGCA CPL papers, Class 1 medical, airline assessments",
        riasec="RI", wlb="Demanding", remote="Completely On-site",
        mid=(2500000, 5000000), senior=(4000000, 9000000),
        related=["air-force-officer"],
        institutes=[
            ("DGCA-approved flying school (India)", "Aviation", "CPL + medical", "Budget ₹40–80L typical; verify the school"),
            ("IGIA / IGRUA-type academies", "Aviation", "Institute + DGCA", "More structured than a random FTO"),
        ],
        steps=[
            ("After Class 10", "Science PCM. Get a Class 2 medical early to know if you clear it.", 1),
            ("After Class 12", "Do not pay a large deposit before checking DGCA approval and aircraft hours.", 2),
            ("Skill Development", "Ground school + flying hours. Airline jobs come after CPL + type rating.", 3),
        ],
    ),
    dict(
        slug="cybersecurity-engineer",
        name="Cybersecurity Engineer", cluster="tech",
        description="Defends networks and apps — SOC, pentest, cloud security or GRC. Shortage role across Indian IT and BFSI.",
        demand="Very High", salary_min=500000, salary_max=2800000,
        skills="Networking, Linux, Threat Analysis, Cloud Security",
        ai_impact="Detection is model-assisted; response and architecture stay human.",
        education_path="B.Tech/BCA/B.Sc CS plus labs. CompTIA Security+, CEH or OSCP help after you can actually hack a lab.",
        exams="JEE Main / CUET for the degree; certifications later",
        riasec="IR", wlb="Average", remote="Hybrid",
        mid=(1000000, 2500000), senior=(1800000, 4500000),
        related=["software-engineer", "data-engineer", "forensic-scientist"],
        institutes=[
            ("B.Tech CSE/IT at NIT/good state college", "Engineering", "JEE Main", "Then a home lab and one cert"),
        ],
        steps=[
            ("After Class 10", "Science PCM. Learn how networks actually work.", 1),
            ("After Class 12", "B.Tech/BCA. Build a home lab in year one — not just watch YouTube.", 2),
            ("Internships", "SOC or app-sec internship. Publish write-ups, not just certificates.", 3),
        ],
    ),
    dict(
        slug="machine-learning-engineer",
        name="Machine Learning Engineer", cluster="tech",
        description="Puts models into production — training pipelines, evaluation and MLOps. Different from a data analyst.",
        demand="Very High", salary_min=700000, salary_max=4000000,
        skills="Python, ML, SQL, Software Engineering",
        ai_impact="The job is building AI systems; tool churn is high, fundamentals are not.",
        education_path="B.Tech CS / B.Sc Stats or Maths, then strong projects. M.Tech/M.Sc helps for research-y teams.",
        exams="JEE Main, GATE (for M.Tech), CUET",
        riasec="I", wlb="Good", remote="Hybrid",
        mid=(1500000, 3500000), senior=(2500000, 6000000),
        related=["data-scientist", "data-engineer", "software-engineer"],
        institutes=[
            ("IIT / NIT / IIIT CS", "Engineering", "JEE", "Still the cleanest campus path"),
            ("M.Tech/M.Sc AI or DS", "University", "GATE / institute", "Useful if the bachelor's was not CS"),
        ],
        steps=[
            ("After Class 10", "Science PCM. Maths is non-negotiable.", 1),
            ("After Class 12", "B.Tech CS or a quantitative B.Sc. Learn Python properly.", 2),
            ("During Graduation", "One end-to-end project in production, not 20 Kaggle bronze medals.", 3),
        ],
    ),
    dict(
        slug="data-engineer",
        name="Data Engineer", cluster="tech",
        description="Builds the pipelines and warehouses that analysts and ML teams sit on. Often hired faster than data scientists.",
        demand="Very High", salary_min=600000, salary_max=3200000,
        skills="SQL, Python, Spark/Warehouses, Data Modelling",
        ai_impact="ETL tools improve; modelling messy business data stays human.",
        education_path="B.Tech/BCA/B.Sc plus serious SQL. Cloud warehouse certifications help after the basics.",
        exams="JEE Main, CUET",
        riasec="IR", wlb="Good", remote="Hybrid",
        mid=(1200000, 2800000), senior=(2000000, 4500000),
        related=["data-analyst", "machine-learning-engineer", "software-engineer"],
        institutes=[
            ("B.Tech CSE/IT or B.Sc CS", "Engineering", "JEE / CUET", "SQL + one cloud warehouse is the floor"),
        ],
        steps=[
            ("After Class 10", "Science PCM.", 1),
            ("After Class 12", "CS-ish bachelor's. Master SQL before you chase Spark memes.", 2),
            ("Internships", "One pipeline internship. Document a before/after data model.", 3),
        ],
    ),
    dict(
        slug="cloud-engineer",
        name="Cloud Engineer", cluster="tech",
        description="Designs and runs AWS/Azure/GCP systems — compute, networking, IAM and cost control.",
        demand="Very High", salary_min=500000, salary_max=2800000,
        skills="Linux, Networking, AWS/Azure/GCP, Infrastructure as Code",
        ai_impact="Consoles get easier; architecture and incidents stay human.",
        education_path="B.Tech/BCA plus a real cloud account. Associate-level certs help after you have broken things yourself.",
        exams="JEE Main, CUET",
        riasec="RI", wlb="Average", remote="Hybrid",
        mid=(1000000, 2400000), senior=(1800000, 4000000),
        related=["software-engineer", "cybersecurity-engineer", "data-engineer"],
        institutes=[
            ("B.Tech CSE/IT or BCA", "Engineering", "JEE / CUET", "Then AWS/Azure associate after a lab"),
        ],
        steps=[
            ("After Class 10", "Science PCM.", 1),
            ("After Class 12", "CS degree. Use the free cloud tier in year one.", 2),
            ("Skill Development", "Linux + networking first, certification second.", 3),
        ],
    ),
    dict(
        slug="electrical-engineer",
        name="Electrical Engineer", cluster="engineering",
        description="Designs and maintains power, electronics and electrical systems — utilities, manufacturing, EVs and buildings.",
        demand="High", salary_min=350000, salary_max=1800000,
        skills="Circuits, Power Systems, MATLAB/PLC, Safety",
        ai_impact="Simulation helps; site and grid work stay licensed/human.",
        education_path="B.Tech/BE or diploma in Electrical / EEE. GATE for PSU and M.Tech.",
        exams="JEE Main, state CET, GATE",
        riasec="RI", wlb="Average", remote="Mostly On-site",
        mid=(600000, 1500000), senior=(1200000, 2800000),
        related=["mechanical-engineer", "civil-engineer"],
        institutes=[
            ("IIT / NIT / good state EE", "Engineering", "JEE / CET", "Core + software skills both useful"),
        ],
        steps=[
            ("After Class 10", "Science PCM or a polytechnic diploma.", 1),
            ("After Class 12", "JEE / CET. Learn circuits with a kit, not only theory.", 2),
            ("Internships", "Utility, EV or manufacturing internship. GATE if you want a PSU.", 3),
        ],
    ),
    dict(
        slug="product-manager",
        name="Product Manager", cluster="business",
        description="Decides what to build and why — discovery, roadmaps and delivery with engineering and design.",
        demand="High", salary_min=800000, salary_max=3500000,
        skills="User Research, Prioritisation, Communication, Analytics",
        ai_impact="Specs draft faster; choosing the problem stays human.",
        education_path="Any strong bachelor's (often B.Tech or BBA) + shipped work. MBA is optional, not the entry ticket.",
        exams="JEE / CUET for the bachelor's; CAT only if you want an MBA later",
        riasec="EI", wlb="Demanding", remote="Hybrid",
        mid=(1500000, 3500000), senior=(2500000, 6000000),
        related=["ux-designer", "software-engineer", "management-consultant"],
        institutes=[
            ("B.Tech or BBA from a good college + internships", "Mixed", "JEE / CUET", "Shipped projects beat a PM certificate"),
        ],
        steps=[
            ("After Class 10", "Any stream; PCM if you want the engineering route.", 1),
            ("After Class 12", "A rigorous bachelor's. Join a campus product/startup club.", 2),
            ("Internships", "APM internship or a real side product. Write crisp case notes.", 3),
        ],
    ),
    dict(
        slug="management-consultant",
        name="Management Consultant", cluster="business",
        description="Solves strategy and operations problems for companies, usually after a campus or lateral hire into a firm.",
        demand="High", salary_min=800000, salary_max=4000000,
        skills="Structured Problem Solving, Communication, Excel/Slides, Industry Research",
        ai_impact="Desk research is faster; client judgment and synthesis stay human.",
        education_path="Top bachelor's or an IIM/ISB MBA. Case interview practice is the real exam.",
        exams="JEE / CUET / CAT (MBA route)",
        riasec="EI", wlb="Highly Demanding", remote="Hybrid",
        mid=(1800000, 4000000), senior=(3000000, 7000000),
        related=["product-manager", "economist", "chartered-accountant"],
        institutes=[
            ("IIT / SRCC / top bachelor's then campus consulting", "University", "JEE / CUET", "Case books matter more than another certificate"),
            ("IIM / ISB MBA", "MBA", "CAT / GMAT", "Classic later entry"),
        ],
        steps=[
            ("After Class 10", "Any rigorous stream.", 1),
            ("After Class 12", "A brand-name or very rigorous bachelor's helps. Learn to write clearly.", 2),
            ("Internships", "One strategy/ops internship. Practise case interviews in year three.", 3),
        ],
    ),
    dict(
        slug="special-educator",
        name="Special Educator", cluster="social",
        description="Teaches students with disabilities in inclusive schools, special schools and therapy centres. RCI-recognised training is what employers look for.",
        demand="High", salary_min=250000, salary_max=800000,
        skills="IEP Planning, Disability Pedagogy, Patience, Family Counselling",
        ai_impact="Adaptive content helps; the relationship is the job.",
        education_path="RCI-recognised B.Ed Special Education or D.Ed SE after 12th/graduation. CTET paper with special-ed focus where applicable.",
        exams="RCI-recognised programme admissions, CTET",
        riasec="S", wlb="Demanding", remote="Mostly On-site",
        mid=(350000, 700000), senior=(600000, 1200000),
        related=["teacher", "psychologist"],
        institutes=[
            ("RCI-recognised B.Ed SE colleges", "Education", "Institute / CUET", "Check the RCI list before you pay fees"),
        ],
        steps=[
            ("After Class 10", "Any stream. Volunteer with a special school if you can.", 1),
            ("After Class 12", "D.Ed SE or a bachelor's then B.Ed SE. Unrecognised diplomas are a trap.", 2),
            ("First Job", "Inclusive school or NGO. Keep your RCI registration current.", 3),
        ],
    ),
    dict(
        slug="economist",
        name="Economist", cluster="business",
        description="Researches markets, policy and development for think tanks, banks, government and consulting.",
        demand="High", salary_min=400000, salary_max=2000000,
        skills="Micro/Macro, Econometrics, Writing, Data Analysis",
        ai_impact="Data pulls are faster; causal claims and policy advice stay human.",
        education_path="BA/B.Sc Economics (Hons) then MA/M.Sc. ISI/DSE/IGIDR are the research heavyweights.",
        exams="CUET, CUET-PG, ISI MSQE, IIT JAM (economics where offered)",
        riasec="I", wlb="Good", remote="Hybrid",
        mid=(800000, 2000000), senior=(1500000, 3500000),
        related=["actuary", "statistician", "rbi-grade-b"],
        institutes=[
            ("Delhi School of Economics / ISI / top Eco (H)", "University", "CUET / ISI", "MA is the usual professional floor"),
        ],
        steps=[
            ("After Class 10", "Commerce or Arts with maths, or PCM.", 1),
            ("After Class 12", "Economics honours. Do not drop maths if you can help it.", 2),
            ("During Graduation", "One empirical paper. Then MA or a research RA job.", 3),
        ],
    ),
    dict(
        slug="statistician",
        name="Statistician", cluster="science",
        description="Designs surveys and experiments and analyses data for government, pharma, finance and tech.",
        demand="High", salary_min=400000, salary_max=2000000,
        skills="Probability, Inference, R/Python, Survey Design",
        ai_impact="Software estimates faster; design and interpretation stay human.",
        education_path="B.Sc Statistics / Math, then M.Stat/M.Sc. ISI is the gold standard.",
        exams="CUET, ISI admission, IIT JAM",
        riasec="IC", wlb="Good", remote="Hybrid",
        mid=(800000, 2000000), senior=(1500000, 3500000),
        related=["actuary", "data-scientist", "economist"],
        institutes=[
            ("ISI Kolkata / Delhi M.Stat", "Institute", "ISI exam", "Best statistics brand in India"),
            ("B.Sc Stats at a good university", "University", "CUET", "Then JAM or ISI"),
        ],
        steps=[
            ("After Class 10", "Keep maths. PCM or Commerce with maths.", 1),
            ("After Class 12", "B.Sc Statistics. Learn R or Python in year one.", 2),
            ("During Graduation", "A real dataset project. ISI/JAM if you want the research path.", 3),
        ],
    ),
    dict(
        slug="biotechnologist",
        name="Biotechnologist", cluster="science",
        description="Applies biology in labs — pharma, agri-biotech, diagnostics and research institutes.",
        demand="High", salary_min=300000, salary_max=1200000,
        skills="Lab Technique, Molecular Biology, Documentation, Analysis",
        ai_impact="Bioinformatics grows; wet-lab skill still hires.",
        education_path="B.Sc/B.Tech Biotechnology after PCB or PCM. M.Sc/M.Tech for decent research or industry roles.",
        exams="CUET, JEE (B.Tech), GATE-BT / JAM for postgrad",
        riasec="IR", wlb="Average", remote="Mostly On-site",
        mid=(500000, 1200000), senior=(900000, 2200000),
        related=["environmental-scientist", "forensic-scientist"],
        institutes=[
            ("B.Tech Biotech at a good college", "Engineering", "JEE / state CET", "Then a lab internship"),
            ("B.Sc then IIT JAM / GATE-BT", "University", "CUET then JAM", "Common research path"),
        ],
        steps=[
            ("After Class 10", "Science PCB or PCM.", 1),
            ("After Class 12", "B.Sc or B.Tech Biotech. A master's is often needed for a good lab role.", 2),
            ("Internships", "One wet-lab internship. Keep a lab notebook like a professional.", 3),
        ],
    ),
    dict(
        slug="agricultural-scientist",
        name="Agricultural Scientist", cluster="science",
        description="Research and extension in crops, soil, livestock or agri-economics — ICAR institutes, state agri universities and industry.",
        demand="High", salary_min=350000, salary_max=1200000,
        skills="Agronomy/Soil/Horticulture, Field Trials, Extension, Data",
        ai_impact="Remote sensing helps; field work and farmer trust stay human.",
        education_path="B.Sc Agriculture (4 years) via ICAR / state exam, then M.Sc and ARS/NET if you want ICAR scientist posts.",
        exams="ICAR AIEEA / CUET-ICAR, state agri CET, ICAR AICE-JRF/SRF",
        riasec="RI", wlb="Average", remote="Mostly On-site",
        mid=(550000, 1100000), senior=(900000, 1800000),
        related=["environmental-scientist", "biotechnologist"],
        institutes=[
            ("State agricultural university / ICAR college", "Agriculture", "ICAR / state CET", "4-year B.Sc Agri"),
        ],
        steps=[
            ("After Class 10", "PCB or PCM. Rural background is not required.", 1),
            ("After Class 12", "B.Sc Agriculture. This is not a 'fallback if NEET fails' — treat it as a first choice.", 2),
            ("Internships", "KVK / research-farm training. ARS later if you want scientist grade.", 3),
        ],
    ),
    dict(
        slug="environmental-scientist",
        name="Environmental Scientist", cluster="science",
        description="Assesses pollution, EIA and conservation for consultancies, regulators and NGOs.",
        demand="High", salary_min=300000, salary_max=1200000,
        skills="EIA, GIS, Environmental Law basics, Field Sampling",
        ai_impact="Satellite data helps; fieldwork and clear writing stay human.",
        education_path="B.Sc Environmental Science / related, then M.Sc. GATE-ES or NET for research/PSU-ish paths.",
        exams="CUET, CUET-PG, GATE-ES",
        riasec="IR", wlb="Good", remote="Hybrid",
        mid=(500000, 1100000), senior=(900000, 2000000),
        related=["agricultural-scientist", "forensic-scientist", "civil-engineer"],
        institutes=[
            ("B.Sc/M.Sc Environmental Science at a central/state univ.", "University", "CUET", "GIS skill is a hiring edge"),
        ],
        steps=[
            ("After Class 10", "Science PCB or PCM.", 1),
            ("After Class 12", "Env-sci or a related B.Sc. Learn QGIS early.", 2),
            ("Internships", "EIA consultancy or forest/pollution-control internship.", 3),
        ],
    ),
    dict(
        slug="forensic-scientist",
        name="Forensic Scientist", cluster="science",
        description="Analyses physical evidence for police and courts — chemistry, biology, digital or questioned documents.",
        demand="Medium", salary_min=350000, salary_max=1000000,
        skills="Lab Analysis, Documentation, Chain of Custody, Court Testimony",
        ai_impact="Instruments improve; chain of custody and testimony stay human.",
        education_path="B.Sc Forensic Science or Chemistry/Biology, then M.Sc. FSL jobs go through SSC/state PSC or institute recruitment.",
        exams="CUET, university tests, SSC/state FSL notifications",
        riasec="IC", wlb="Average", remote="Completely On-site",
        mid=(500000, 1000000), senior=(800000, 1600000),
        related=["cybersecurity-engineer", "biotechnologist"],
        institutes=[
            ("NFSU / good university forensic M.Sc", "University", "CUET / institute", "Chemistry or biology bachelor's also works"),
        ],
        steps=[
            ("After Class 10", "Science PCB or PCM.", 1),
            ("After Class 12", "B.Sc Forensic or Chemistry/Biology. Crime-show TV is not the job.", 2),
            ("Internships", "FSL or college lab project with proper documentation.", 3),
        ],
    ),
    dict(
        slug="animation-artist",
        name="Animator / Motion Designer", cluster="creative",
        description="Creates 2D/3D animation and motion graphics for films, games, ads and explainers.",
        demand="High", salary_min=250000, salary_max=1500000,
        skills="Drawing/3D, Timing, After Effects/Blender, Storytelling",
        ai_impact="In-betweening gets automated; performance and taste stay human.",
        education_path="B.Des Animation or a strong self-taught reel. NID/private animation schools. The reel hires you.",
        exams="NID DAT, UCEED, institute tests",
        riasec="AR", wlb="Demanding", remote="Hybrid",
        mid=(450000, 1200000), senior=(900000, 2500000),
        related=["graphic-designer", "journalist"],
        institutes=[
            ("NID / good private animation schools", "Design", "NID DAT / institute", "A 60-second reel beats a 4-year brochure"),
        ],
        steps=[
            ("After Class 10", "Any stream. Draw every day.", 1),
            ("After Class 12", "Animation B.Des or a disciplined self-taught year + Blender/AE.", 2),
            ("Internships", "Studio internship. Ship a finished short, not only class assignments.", 3),
        ],
    ),
    dict(
        slug="urban-planner",
        name="Urban / Town Planner", cluster="science",
        description="Plans cities, transport and land use for development authorities, consultancies and ULBs.",
        demand="High", salary_min=350000, salary_max=1400000,
        skills="GIS, Land Use, Transport Basics, Stakeholder Work",
        ai_impact="GIS models improve; politics of land stay human.",
        education_path="B.Plan (5 years) after 12th, or B.Arch/B.Tech then M.Plan. GATE and ITPI routes exist.",
        exams="JEE Main (B.Planning), NATA (if via B.Arch), GATE (M.Plan)",
        riasec="IE", wlb="Average", remote="Hybrid",
        mid=(600000, 1300000), senior=(1100000, 2200000),
        related=["architect", "civil-engineer", "environmental-scientist"],
        institutes=[
            ("SPA Delhi / CEPT / good B.Plan schools", "Planning", "JEE B.Planning", "5-year professional degree"),
        ],
        steps=[
            ("After Class 10", "PCM is typical.", 1),
            ("After Class 12", "JEE Main B.Planning paper, or B.Arch then M.Plan.", 2),
            ("Internships", "Development authority or planning-studio internship. Learn QGIS.", 3),
        ],
    ),
    dict(
        slug="social-worker",
        name="Social Worker", cluster="social",
        description="Works with communities, children, health or livelihoods in NGOs, CSR, hospitals and government schemes.",
        demand="High", salary_min=220000, salary_max=800000,
        skills="Field Work, Listening, Case Work, Programme Basics",
        ai_impact="Reporting tools help; trust in the field stays human.",
        education_path="BSW then MSW (TISS and good university departments). Any bachelor's + MSW is common.",
        exams="CUET, TISS/institute MA/MSW tests",
        riasec="S", wlb="Demanding", remote="Mostly On-site",
        mid=(350000, 700000), senior=(600000, 1200000),
        related=["special-educator", "psychologist", "teacher"],
        institutes=[
            ("TISS and good university MSW", "University", "CUET / institute", "Fieldwork quality matters more than the brochure"),
        ],
        steps=[
            ("After Class 10", "Any stream. Volunteer with a real organisation.", 1),
            ("After Class 12", "BSW or any bachelor's then MSW. Unpaid 'internship mills' teach little.", 2),
            ("Internships", "One sustained field placement, not five certificate camps.", 3),
        ],
    ),
    dict(
        slug="veterinarian",
        name="Veterinarian (B.V.Sc)", cluster="healthcare",
        description="Treats animals in clinics, farms, government AH departments and industry. Five-and-a-half-year professional degree.",
        demand="High", salary_min=350000, salary_max=1200000,
        skills="Animal Clinical Skills, Surgery Basics, Epidemiology, Client Communication",
        ai_impact="Diagnostics assist; handling animals and surgery stay human.",
        education_path="B.V.Sc & A.H. (5.5 years) after PCB via NEET-UG in most states. State AH jobs after the degree.",
        exams="NEET-UG, state counselling",
        riasec="RI", wlb="Demanding", remote="Completely On-site",
        mid=(500000, 1100000), senior=(800000, 2000000),
        related=["doctor-mbbs", "agricultural-scientist"],
        institutes=[
            ("State veterinary college", "Veterinary", "NEET-UG", "5.5 years including internship"),
        ],
        steps=[
            ("After Class 10", "Science PCB.", 1),
            ("After Class 12", "NEET-UG, then veterinary counselling (not only MBBS lists).", 2),
            ("First Job", "Clinic, dairy/poultry industry, or state AH department.", 3),
        ],
    ),
    dict(
        slug="chef",
        name="Chef", cluster="creative",
        description="Cooks and runs kitchens in hotels, restaurants and cloud kitchens. Craft plus stamina; formal hotel school helps but is not the only door.",
        demand="High", salary_min=180000, salary_max=1200000,
        skills="Cooking Technique, Kitchen Hygiene, Menu Costing, Teamwork",
        ai_impact="Recipes are everywhere; consistent execution on a Friday night is not.",
        education_path="BHM / craftsmanship certificate / apprenticeship in a serious kitchen. NCHMCT JEE if you want IHM.",
        exams="NCHMCT JEE (optional)",
        riasec="RA", wlb="Highly Demanding", remote="Completely On-site",
        mid=(350000, 900000), senior=(700000, 2000000),
        related=["hotel-manager"],
        institutes=[
            ("IHM via NCHMCT", "Hospitality", "NCHMCT JEE", "Kitchen + management mix"),
            ("Apprenticeship in a reputable restaurant", "Trade", "None", "Often faster than a weak private degree"),
        ],
        steps=[
            ("After Class 10", "Any stream. Cook at home with recipes you can repeat.", 1),
            ("After Class 12", "IHM or a kitchen apprenticeship. Ask about hours and stipend before you join.", 2),
            ("First Job", "Commis → chef de partie. Build a small repertoire, not only Instagram plates.", 3),
        ],
    ),
]


EXTRA_EXAMS = [
    dict(exam_name="IBPS PO / SBI PO", exam_code="IBPS_PO", typical_window="Aug–Nov (typical)",
         typical_month=8, next_cycle="2026–27", education_level="Undergraduate",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="business",
         official_url="https://www.ibps.in",
         notes="Graduate bank-officer exams. Recur most years. Age caps apply."),
    dict(exam_name="CDS", exam_code="CDS", typical_window="Apr & Sep",
         typical_month=4, next_cycle="2026–27", education_level="Undergraduate",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="law,engineering",
         official_url="https://upsc.gov.in",
         notes="Combined Defence Services after graduation. SSB follows the written exam."),
    dict(exam_name="AFCAT", exam_code="AFCAT", typical_window="Feb & Aug (typical)",
         typical_month=2, next_cycle="2026–27", education_level="Undergraduate",
         streams="pcm,pcmb", clusters="law,engineering",
         official_url="https://afcat.cdac.in",
         notes="Indian Air Force graduate entry — flying, technical and ground duty."),
    dict(exam_name="CSEET / CS Executive", exam_code="CS", typical_window="Multiple windows",
         typical_month=5, next_cycle="2026–27", education_level="Class 11-12",
         streams="commerce,pcm,pcmb,arts", clusters="business",
         official_url="https://www.icsi.edu",
         notes="Company Secretary entry after Class 12. Then Executive and Professional."),
    dict(exam_name="CMA Foundation", exam_code="CMA", typical_window="Jun & Dec (typical)",
         typical_month=6, next_cycle="2026–27", education_level="Class 11-12",
         streams="commerce,pcm,pcmb", clusters="business",
         official_url="https://icmai.in",
         notes="Cost and Management Accountancy. Strong fit for manufacturing/PSU costing."),
    dict(exam_name="NCHMCT JEE", exam_code="NCHMCT", typical_window="May",
         typical_month=5, next_cycle="2026–27", education_level="Class 11-12",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="business,creative",
         official_url="https://nchmjee.nta.nic.in",
         notes="IHM / hotel-management bachelor's."),
    dict(exam_name="ICAR / CUET-ICAR", exam_code="ICAR", typical_window="May–Jun",
         typical_month=5, next_cycle="2026–27", education_level="Class 11-12",
         streams="pcb,pcm,pcmb", clusters="science",
         official_url="https://icar.org.in",
         notes="B.Sc Agriculture and allied programmes at SAUs."),
    dict(exam_name="CAT", exam_code="CAT", typical_window="Nov",
         typical_month=11, next_cycle="2026–27", education_level="Undergraduate",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="business",
         official_url="https://iimcat.ac.in",
         notes="IIM and many MBA programmes. Take it in the final year or after a job."),
    dict(exam_name="UGC NET", exam_code="UGC_NET", typical_window="Jun & Dec (typical)",
         typical_month=6, next_cycle="2026–27", education_level="Postgraduate",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="science,social,business",
         official_url="https://ugcnet.nta.ac.in",
         notes="Assistant professor eligibility and JRF. Master's required."),
    dict(exam_name="RBI Grade B", exam_code="RBI_B", typical_window="Sep–Nov (typical)",
         typical_month=9, next_cycle="2026–27", education_level="Undergraduate",
         streams="pcm,pcb,pcmb,commerce,arts", clusters="business",
         official_url="https://www.rbi.org.in",
         notes="Direct officer at RBI. Phase I, II and interview. Age/attempts capped."),
]


EXTRA_SCHOLARSHIPS = [
    dict(name="Ishan Uday Special Scholarship (NER)", provider="UGC", type="Government",
         description="Scholarship for students with domicile in the North Eastern Region starting a general-degree course.",
         education_level="UG", states="Assam,Arunachal Pradesh,Manipur,Meghalaya,Mizoram,Nagaland,Sikkim,Tripura",
         categories="All", gender="All", income_ceiling=450000,
         amount="Rs 5,400–7,800/month", deadline="2026-10-31",
         apply_url="https://scholarships.gov.in",
         documents="NER domicile, income certificate, admission proof, Aadhaar"),
    dict(name="Post-Matric Scholarship for ST Students", provider="Ministry of Tribal Affairs", type="Government",
         description="Post-matric financial aid for Scheduled Tribe students.",
         education_level="Class 11-PG", states="All", categories="ST",
         gender="All", income_ceiling=250000, amount="Tuition + maintenance",
         deadline="2026-11-30", apply_url="https://scholarships.gov.in",
         documents="ST certificate, income certificate, admission proof, bank passbook"),
    dict(name="LIC Golden Jubilee Scholarship", provider="LIC", type="Corporate",
         description="Merit-cum-means support for students from economically weaker families in Class 12 and after.",
         education_level="Class 11-UG", states="All", categories="All",
         gender="All", income_ceiling=250000, amount="Rs 20,000–40,000/year",
         deadline="2026-12-10", apply_url="https://licindia.in",
         documents="Income certificate, marksheet, admission proof"),
    dict(name="ONGC Scholarship for SC/ST/OBC/General-EWS", provider="ONGC", type="Corporate",
         description="Scholarship for meritorious engineering, geology and MBA students from reserved and EWS categories.",
         education_level="UG", states="All", categories="SC,ST,OBC,EWS",
         gender="All", income_ceiling=200000, amount="Rs 48,000/year",
         deadline="2026-10-20", apply_url="https://www.ongcindia.com",
         documents="Caste/EWS certificate, income certificate, marksheet"),
    dict(name="Kotak Kanya Scholarship", provider="Kotak Education Foundation", type="Corporate",
         description="Support for meritorious girls entering professional undergraduate courses.",
         education_level="UG", states="All", categories="All",
         gender="Female", income_ceiling=600000, amount="Up to Rs 1.5 lakh/year",
         deadline="2026-09-30", apply_url="https://www.kotak.com",
         documents="Class 12 marksheet, income certificate, admission letter"),
    dict(name="e-Grantz (Kerala)", provider="Govt. of Kerala", type="State",
         description="Fee concession and stipend portal for eligible Kerala students across courses.",
         education_level="Class 11-PG", states="Kerala", categories="All",
         gender="All", income_ceiling=None, amount="Fee concession / stipend as notified",
         deadline="2026-11-15", apply_url="https://www.egrantz.kerala.gov.in",
         documents="Domicile, income/caste as applicable, admission proof"),
    dict(name="Bihar Post-Matric Scholarship", provider="Govt. of Bihar", type="State",
         description="Post-matric scholarship for eligible Bihar-domicile students (category rules as notified).",
         education_level="Class 11-PG", states="Bihar", categories="SC,ST,OBC,EWS",
         gender="All", income_ceiling=250000, amount="As per state notification",
         deadline="2026-11-30", apply_url="https://www.pmsonline.bih.nic.in",
         documents="Domicile, caste, income, admission proof"),
    dict(name="UP Post-Matric Scholarship", provider="Govt. of Uttar Pradesh", type="State",
         description="State post-matric scholarship for eligible UP students via the scholarship portal.",
         education_level="Class 11-PG", states="Uttar Pradesh", categories="SC,ST,OBC,General",
         gender="All", income_ceiling=250000, amount="As per state notification",
         deadline="2026-11-30", apply_url="https://scholarship.up.gov.in",
         documents="Domicile, income, caste if applicable, admission proof"),
]
